services:
  app:
    profiles: ["prod"]  # This service will only run when explicitly included
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mealsync
      - JWT_SECRET=your_jwt_secret_key
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key
      - SERVER_PORT=8080
    volumes:
      - .:/app
    networks:
      - mealsync-network
    command: sh -c "
      sleep 5 &&
      go run cmd/main.go"

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mealsync
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - mealsync-network

  migrate:
    image: migrate/migrate
    volumes:
      - ./internal/db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@db:5432/mealsync?sslmode=disable", "up"]
    depends_on:
      - db
    networks:
      - mealsync-network

volumes:
  postgres-data:

networks:
  mealsync-network:
    driver: bridge 